[program:laravel-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /Users/panfiloveshow/Documents/Товары\ бекенд/products-backend/artisan queue:work --sleep=3 --tries=3 --max-time=3600
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=panfiloveshow
numprocs=2
redirect_stderr=true
stdout_logfile=/Users/panfiloveshow/Documents/Товары\ бекенд/products-backend/storage/logs/worker.log
stopwaitsecs=3600
